# coding: utf-8

"""
    IT Glue API in OpenAPI Spec

    This is the IT Glue API implemented in OpenAPI 3.0 specification.  NAMING CONVENTIONS  We try to match the ITGlue API naming conventions as closely as possible. In descriptions of summaries a different word may be used to match common English. For instance, the ITGlue API uses the word \"index\" to describe a GET method, but the description will use the word \"list\" instead.  index: Used to get a list of resources. I.e., multiple resources.    HTTP Method: GET   Example: indexOrganizations show: Used to get a single resource. I.e., one resource.     HTTP Method: GET     Example: showOrganization create: Used to create a new resource.     HTTP Method: POST     Example: createOrganization update: Used to update an existing resource.     HTTP Method: PATCH     Example: updateOrganization  ITGLUE API DOCUMENTATION - [Reference](https://api.itglue.com/developer/)  # noqa: E501

    The version of the OpenAPI document: 0.0.01
    Contact: jonathan.addington@jmaddington.com
    Generated by: https://openapi-generator.tech
"""

from itglue.paths.organization_statuses.post import CreateOrganizationStatus
from itglue.paths.organization_types.post import CreateOrganizationType
from itglue.paths.organization_statuses.get import IndexOrganizationStatuses
from itglue.paths.organization_types.get import IndexOrganizationTypes
from itglue.paths.organization_types_id.get import ShowOrganizationType
from itglue.paths.organization_types_id.patch import UpdateOrganizationType


class OrganizationTypesApi(
    CreateOrganizationStatus,
    CreateOrganizationType,
    IndexOrganizationStatuses,
    IndexOrganizationTypes,
    ShowOrganizationType,
    UpdateOrganizationType,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
