# coding: utf-8

"""
    IT Glue API in OpenAPI Spec

    This is the IT Glue API implemented in OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io).  Some useful links: - [Reference](https://api.itglue.com/developer/)  # noqa: E501

    The version of the OpenAPI document: 0.0.01
    Contact: jonathan.addington@jmaddington.com
    Generated by: https://openapi-generator.tech
"""

from itglue.paths.organizations.get import OrganizationsGet
from itglue.paths.organizations_id.get import OrganizationsIdGet
from itglue.paths.organizations_id.patch import OrganizationsIdPatch
from itglue.paths.organizations.post import OrganizationsPost


class OrganizationsApi(
    OrganizationsGet,
    OrganizationsIdGet,
    OrganizationsIdPatch,
    OrganizationsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
