# coding: utf-8

"""
    IT Glue API in OpenAPI Spec

    This is the IT Glue API implemented in OpenAPI 3.0 specification.  NAMING CONVENTIONS  We try to match the ITGlue API naming conventions as closely as possible. In descriptions of summaries a different word may be used to match common English. For instance, the ITGlue API uses the word \"index\" to describe a GET method, but the description will use the word \"list\" instead.  index: Used to get a list of resources. I.e., multiple resources.    HTTP Method: GET   Example: indexOrganizations show: Used to get a single resource. I.e., one resource.     HTTP Method: GET     Example: showOrganization create: Used to create a new resource.     HTTP Method: POST     Example: createOrganization update: Used to update an existing resource.     HTTP Method: PATCH     Example: updateOrganization  ITGLUE API DOCUMENTATION - [Reference](https://api.itglue.com/developer/)  # noqa: E501

    The version of the OpenAPI document: 0.0.01
    Contact: jonathan.addington@jmaddington.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import itglue
from itglue.model.organization_status import OrganizationStatus
from itglue import configuration


class TestOrganizationStatus(unittest.TestCase):
    """OrganizationStatus unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
