# coding: utf-8

"""
    IT Glue API in OpenAPI Spec

    This is the IT Glue API implemented in OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io).  Some useful links: - [Reference](https://api.itglue.com/developer/)  # noqa: E501

    The version of the OpenAPI document: 0.0.01
    Contact: jonathan.addington@jmaddington.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import itglue
from itglue.model.organization import Organization
from itglue import configuration


class TestOrganization(unittest.TestCase):
    """Organization unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
